In [ ]:
import numpy as np 
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Bitcoin Historical Data yearly.csv')
df.head(7)

   Jun 05, 2022  29,634.30
0  Jun 04, 2022  29,864.30
1  Jun 03, 2022  29,700.90
2  Jun 02, 2022  30,455.50
3  Jun 01, 2022  29,798.50
4  May 31, 2022  31,793.40
5  May 30, 2022  31,723.30
6  May 29, 2022  29,465.20

In [ ]:
#Remove the Date column
df.drop(['Date'], 1, inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

In [ ]:
#Show the first 7 rows of the new data set
df.head(7)

       Price
0  29,634.30
1  29,864.30
2  29,700.90
3  30,455.50
4  29,798.50
5  31,793.40
6  31,723.30

In [ ]:
#A variable for predicting 'n' days out into the future
prediction_days = 10 #n = 30 days

#Create another column (the target or dependent variable) shifted 'n' units up
df['Prediction'] = df[['Price']].shift(-prediction_days)

In [ ]:
#Show the first 7 rows of the new data set
df.head(7)

       Price Prediction
0  29,634.30  29,203.50
1  29,864.30  29,540.60
2  29,700.90  29,648.70
3  30,455.50  29,093.30
4  29,798.50  30,286.60
5  31,793.40  29,434.60
6  31,723.30  29,178.60

In [ ]:
#Show the last 7 rows of the new data set
df.tail(7)

         Price Prediction
359  37,314.60        NaN
360  36,649.40        NaN
361  37,332.20        NaN
362  33,382.90        NaN
363  33,578.00        NaN
364  35,815.40        NaN
365  35,520.00        NaN

In [ ]:
#CREATE THE INDEPENDENT DATA SET (X)

# Convert the dataframe to a numpy array and drop the prediction column
X = np.array(df.drop(['Prediction'],1))

#Remove the last 'n' rows where 'n' is the prediction_days
X= X[:len(df)-prediction_days]
print(X)

[['29,634.30']
 ['29,864.30']
 ['29,700.90']
 ['30,455.50']
 ['29,798.50']
 ['31,793.40']
 ['31,723.30']
 ['29,465.20']
 ['29,027.10']
 ['28,601.20']
 ['29,203.50']
 ['29,540.60']
 ['29,648.70']
 ['29,093.30']
 ['30,286.60']
 ['29,434.60']
 ['29,178.60']
 ['30,305.90']
 ['28,683.70']
 ['30,437.50']
 ['29,849.00']
 ['31,308.70']
 ['30,080.40']
 ['29,284.40']
 ['28,976.00']
 ['29,068.20']
 ['31,007.50']
 ['30,095.00']
 ['34,060.00']
 ['35,468.00']
 ['36,009.00']
 ['36,544.00']
 ['39,688.00']
 ['37,718.00']
 ['38,514.00']
 ['38,461.00']
 ['37,650.00']
 ['38,581.00']
 ['39,748.00']
 ['39,243.00']
 ['38,113.00']
 ['40,427.00']
 ['39,464.00']
 ['39,418.00']
 ['39,709.00']
 ['40,482.00']
 ['41,368.00']
 ['41,503.00']
 ['40,803.00']
 ['39,703.00']
 ['40,382.00']
 ['40,560.00']
 ['39,936.00']
 ['41,133.00']
 ['40,078.00']
 ['39,497.00']
 ['42,138.00']
 ['42,767.00']
 ['42,275.00']
 ['43,448.00']
 ['43,173.00']
 ['45,506.00']
 ['46,629.00']
 ['46,407.00']
 ['45,811.00']
 ['46,297.00']
 ['45,525.00']
 ['47,075.00']
 ['47,449.00']
 ['47,105.00']
 ['46,859.00']
 ['44,548.00']
 ['44,331.00']
 ['44,013.00']
 ['42,912.00']
 ['42,373.00']
 ['41,022.00']
 ['41,276.00']
 ['42,233.00']
 ['41,767.80']
 ['40,914.80']
 ['41,118.70']
 ['39,285.70']
 ['39,671.10']
 ['37,792.40']
 ['38,814.30']
 ['38,730.20']
 ['39,416.30']
 ['41,929.00']
 ['38,744.80']
 ['38,024.80']
 ['38,403.10']
 ['39,395.80']
 ['39,142.70']
 ['42,463.00']
 ['43,912.80']
 ['44,420.30']
 ['43,188.20']
 ['37,689.10']
 ['39,115.50']
 ['39,209.60']
 ['38,339.20']
 ['37,224.60']
 ['38,248.20']
 ['37,017.70']
 ['38,355.00']
 ['40,090.30']
 ['40,000.10']
 ['40,552.80']
 ['43,883.60']
 ['44,544.40']
 ['42,550.30']
 ['42,061.10']
 ['42,205.20']
 ['42,388.40']
 ['43,521.00']
 ['44,388.90']
 ['44,038.20']
 ['43,833.90']
 ['42,392.20']
 ['41,412.10']
 ['41,567.60']
 ['37,287.80']
 ['36,890.20']
 ['38,709.70']
 ['38,498.60']
 ['37,917.70']
 ['38,170.80']
 ['37,745.10']
 ['37,164.30']
 ['36,800.40']
 ['36,950.60']
 ['36,686.30']
 ['36,269.50']
 ['35,075.20']
 ['36,475.50']
 ['40,715.90']
 ['41,677.80']
 ['42,364.60']
 ['42,209.30']
 ['43,079.10']
 ['43,097.00']
 ['43,073.30']
 ['42,560.00']
 ['43,901.00']
 ['42,733.20']
 ['41,832.20']
 ['41,848.30']
 ['41,672.00']
 ['41,546.70']
 ['43,097.50']
 ['43,425.90']
 ['45,837.30']
 ['46,430.20']
 ['47,311.80']
 ['47,738.00']
 ['46,219.50']
 ['47,123.30']
 ['46,461.70']
 ['47,545.20']
 ['50,678.20']
 ['50,779.90']
 ['50,406.40']
 ['50,786.10']
 ['50,801.00']
 ['48,599.70']
 ['48,902.00']
 ['46,895.20']
 ['46,704.50']
 ['46,856.20']
 ['46,172.20']
 ['47,628.20']
 ['48,871.50']
 ['48,366.50']
 ['46,703.60']
 ['50,081.00']
 ['49,314.50']
 ['47,137.20']
 ['47,596.60']
 ['50,473.90']
 ['50,595.20']
 ['50,562.10']
 ['49,405.50']
 ['49,195.20']
 ['53,631.50']
 ['56,496.00']
 ['57,210.30']
 ['56,882.90']
 ['57,794.80']
 ['57,291.50']
 ['54,765.90']
 ['53,730.90']
 ['58,935.10']
 ['57,171.70']
 ['57,573.20']
 ['56,308.80']
 ['58,714.30']
 ['59,717.60']
 ['58,083.40']
 ['56,955.30']
 ['60,367.80']
 ['60,089.10']
 ['63,597.90']
 ['65,508.20']
 ['64,398.60']
 ['64,134.50']
 ['64,806.70']
 ['64,932.60']
 ['66,904.40']
 ['67,527.90']
 ['63,273.20']
 ['61,483.90']
 ['60,974.30']
 ['61,412.60']
 ['62,918.50']
 ['63,221.70']
 ['60,915.30']
 ['61,309.60']
 ['61,840.10']
 ['62,242.80']
 ['60,582.50']
 ['58,438.10']
 ['60,310.80']
 ['63,067.00']
 ['60,866.50']
 ['61,312.50']
 ['60,690.30']
 ['62,210.20']
 ['65,979.10']
 ['64,278.50']
 ['62,056.30']
 ['61,527.50']
 ['60,861.10']
 ['61,672.50']
 ['57,345.80']
 ['57,380.10']
 ['56,015.90']
 ['57,477.30']
 ['54,687.70']
 ['54,942.50']
 ['53,914.70']
 ['53,783.90']
 ['55,323.20']
 ['51,469.30']
 ['49,227.30']
 ['48,200.10']
 ['47,666.90']
 ['48,146.00']
 ['43,823.30']
 ['41,536.80']
 ['41,022.30']
 ['42,172.60']
 ['43,203.40']
 ['42,686.80']
 ['42,819.90']
 ['44,869.20']
 ['43,551.60']
 ['40,651.30']
 ['42,870.60']
 ['47,238.70']
 ['48,306.70']
 ['47,282.80']
 ['47,748.00']
 ['48,130.60']
 ['47,077.50']
 ['44,949.50']
 ['46,062.30']
 ['45,161.90']
 ['44,842.80']
 ['46,385.60']
 ['46,061.40']
 ['46,779.60']
 ['52,672.10']
 ['51,768.60']
 ['49,918.40']
 ['49,999.00']
 ['49,274.30']
 ['48,819.40']
 ['47,130.40']
 ['46,992.70']
 ['48,777.40']
 ['48,897.10']
 ['49,064.30']
 ['46,831.60']
 ['48,994.50']
 ['47,714.70']
 ['49,539.70']
 ['49,254.50']
 ['48,875.80']
 ['49,324.00']
 ['46,755.90']
 ['44,723.80']
 ['44,691.60']
 ['45,996.30']
 ['46,991.30']
 ['47,081.50']
 ['47,809.10']
 ['44,403.40']
 ['45,564.30']
 ['45,593.80']
 ['46,284.30']
 ['43,792.80']
 ['44,614.20']
 ['42,795.40']
 ['40,867.20']
 ['39,736.90']
 ['38,130.30']
 ['39,168.40']
 ['39,878.30']
 ['41,553.70']
 ['42,203.40']
 ['40,001.40']
 ['40,003.20']
 ['39,452.00']
 ['37,276.60']
 ['35,391.10']
 ['33,824.80']
 ['33,603.30']
 ['32,298.90']
 ['32,131.40']
 ['29,793.80']
 ['30,837.20']
 ['31,785.40']
 ['31,518.60']
 ['31,394.00']
 ['31,840.50']
 ['32,820.70']
 ['32,728.10']
 ['33,113.00']
 ['34,227.70']
 ['33,510.60']
 ['33,797.40']
 ['32,866.30']
 ['33,867.80']
 ['34,225.60']
 ['33,687.80']
 ['35,298.20']
 ['34,742.80']
 ['33,813.40']
 ['33,543.60']
 ['35,026.90']
 ['35,834.70']
 ['34,475.90']
 ['34,678.50']
 ['32,243.40']
 ['31,594.00']
 ['34,665.80']
 ['33,674.30']
 ['32,496.40']
 ['31,692.00']
 ['35,595.80']
 ['35,513.40']
 ['35,749.40']
 ['38,052.00']
 ['38,336.00']
 ['40,156.10']]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  after removing the cwd from sys.path.

In [ ]:
#CREATE THE DEPENDENT DATA SET (y) 
# Convert the dataframe to a numpy array (All of the values including the NaN's)
y = np.array(df['Prediction'])  
# Get all of the y values except the last 'n' rows 
y = y[:-prediction_days] 
print(y)

['29,203.50' '29,540.60' '29,648.70' '29,093.30' '30,286.60' '29,434.60'
 '29,178.60' '30,305.90' '28,683.70' '30,437.50' '29,849.00' '31,308.70'
 '30,080.40' '29,284.40' '28,976.00' '29,068.20' '31,007.50' '30,095.00'
 '34,060.00' '35,468.00' '36,009.00' '36,544.00' '39,688.00' '37,718.00'
 '38,514.00' '38,461.00' '37,650.00' '38,581.00' '39,748.00' '39,243.00'
 '38,113.00' '40,427.00' '39,464.00' '39,418.00' '39,709.00' '40,482.00'
 '41,368.00' '41,503.00' '40,803.00' '39,703.00' '40,382.00' '40,560.00'
 '39,936.00' '41,133.00' '40,078.00' '39,497.00' '42,138.00' '42,767.00'
 '42,275.00' '43,448.00' '43,173.00' '45,506.00' '46,629.00' '46,407.00'
 '45,811.00' '46,297.00' '45,525.00' '47,075.00' '47,449.00' '47,105.00'
 '46,859.00' '44,548.00' '44,331.00' '44,013.00' '42,912.00' '42,373.00'
 '41,022.00' '41,276.00' '42,233.00' '41,767.80' '40,914.80' '41,118.70'
 '39,285.70' '39,671.10' '37,792.40' '38,814.30' '38,730.20' '39,416.30'
 '41,929.00' '38,744.80' '38,024.80' '38,403.10' '39,395.80' '39,142.70'
 '42,463.00' '43,912.80' '44,420.30' '43,188.20' '37,689.10' '39,115.50'
 '39,209.60' '38,339.20' '37,224.60' '38,248.20' '37,017.70' '38,355.00'
 '40,090.30' '40,000.10' '40,552.80' '43,883.60' '44,544.40' '42,550.30'
 '42,061.10' '42,205.20' '42,388.40' '43,521.00' '44,388.90' '44,038.20'
 '43,833.90' '42,392.20' '41,412.10' '41,567.60' '37,287.80' '36,890.20'
 '38,709.70' '38,498.60' '37,917.70' '38,170.80' '37,745.10' '37,164.30'
 '36,800.40' '36,950.60' '36,686.30' '36,269.50' '35,075.20' '36,475.50'
 '40,715.90' '41,677.80' '42,364.60' '42,209.30' '43,079.10' '43,097.00'
 '43,073.30' '42,560.00' '43,901.00' '42,733.20' '41,832.20' '41,848.30'
 '41,672.00' '41,546.70' '43,097.50' '43,425.90' '45,837.30' '46,430.20'
 '47,311.80' '47,738.00' '46,219.50' '47,123.30' '46,461.70' '47,545.20'
 '50,678.20' '50,779.90' '50,406.40' '50,786.10' '50,801.00' '48,599.70'
 '48,902.00' '46,895.20' '46,704.50' '46,856.20' '46,172.20' '47,628.20'
 '48,871.50' '48,366.50' '46,703.60' '50,081.00' '49,314.50' '47,137.20'
 '47,596.60' '50,473.90' '50,595.20' '50,562.10' '49,405.50' '49,195.20'
 '53,631.50' '56,496.00' '57,210.30' '56,882.90' '57,794.80' '57,291.50'
 '54,765.90' '53,730.90' '58,935.10' '57,171.70' '57,573.20' '56,308.80'
 '58,714.30' '59,717.60' '58,083.40' '56,955.30' '60,367.80' '60,089.10'
 '63,597.90' '65,508.20' '64,398.60' '64,134.50' '64,806.70' '64,932.60'
 '66,904.40' '67,527.90' '63,273.20' '61,483.90' '60,974.30' '61,412.60'
 '62,918.50' '63,221.70' '60,915.30' '61,309.60' '61,840.10' '62,242.80'
 '60,582.50' '58,438.10' '60,310.80' '63,067.00' '60,866.50' '61,312.50'
 '60,690.30' '62,210.20' '65,979.10' '64,278.50' '62,056.30' '61,527.50'
 '60,861.10' '61,672.50' '57,345.80' '57,380.10' '56,015.90' '57,477.30'
 '54,687.70' '54,942.50' '53,914.70' '53,783.90' '55,323.20' '51,469.30'
 '49,227.30' '48,200.10' '47,666.90' '48,146.00' '43,823.30' '41,536.80'
 '41,022.30' '42,172.60' '43,203.40' '42,686.80' '42,819.90' '44,869.20'
 '43,551.60' '40,651.30' '42,870.60' '47,238.70' '48,306.70' '47,282.80'
 '47,748.00' '48,130.60' '47,077.50' '44,949.50' '46,062.30' '45,161.90'
 '44,842.80' '46,385.60' '46,061.40' '46,779.60' '52,672.10' '51,768.60'
 '49,918.40' '49,999.00' '49,274.30' '48,819.40' '47,130.40' '46,992.70'
 '48,777.40' '48,897.10' '49,064.30' '46,831.60' '48,994.50' '47,714.70'
 '49,539.70' '49,254.50' '48,875.80' '49,324.00' '46,755.90' '44,723.80'
 '44,691.60' '45,996.30' '46,991.30' '47,081.50' '47,809.10' '44,403.40'
 '45,564.30' '45,593.80' '46,284.30' '43,792.80' '44,614.20' '42,795.40'
 '40,867.20' '39,736.90' '38,130.30' '39,168.40' '39,878.30' '41,553.70'
 '42,203.40' '40,001.40' '40,003.20' '39,452.00' '37,276.60' '35,391.10'
 '33,824.80' '33,603.30' '32,298.90' '32,131.40' '29,793.80' '30,837.20'
 '31,785.40' '31,518.60' '31,394.00' '31,840.50' '32,820.70' '32,728.10'
 '33,113.00' '34,227.70' '33,510.60' '33,797.40' '32,866.30' '33,867.80'
 '34,225.60' '33,687.80' '35,298.20' '34,742.80' '33,813.40' '33,543.60'
 '35,026.90' '35,834.70' '34,475.90' '34,678.50' '32,243.40' '31,594.00'
 '34,665.80' '33,674.30' '32,496.40' '31,692.00' '35,595.80' '35,513.40'
 '35,749.40' '38,052.00' '38,336.00' '40,156.10' '40,529.40' '39,022.90'
 '35,467.50' '37,314.60' '36,649.40' '37,332.20' '33,382.90' '33,578.00'
 '35,815.40' '35,520.00']

In [ ]:
# Split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
x, x_test, y, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# Set prediction_days_array equal to the last 30 rows of the original data set from the price column
prediction_days_array = np.array(df.drop(['Prediction'],1))[-prediction_days:]
print(prediction_days_array)

[['40,529.40']
 ['39,022.90']
 ['35,467.50']
 ['37,314.60']
 ['36,649.40']
 ['37,332.20']
 ['33,382.90']
 ['33,578.00']
 ['35,815.40']
 ['35,520.00']]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

In [ ]:
from sklearn.svm import SVR
# Create and train the Support Vector Machine 
svr_linear = SVR(kernel='linear', C=1e2, gamma=0.00000001)#Create the model

In [ ]:
svr_linear.fit(x, y)

ValueError: ignored

In [ ]:
# Testing Model: Score returns the accuracy of the prediction. 
# The best possible score is 1.0
svr_rbf_confidence = svr_rbf.score(x_test, y_test)
print("svr_rbf accuracy: ", svr_rbf_confidence)

NotFittedError: ignored